<a href="https://colab.research.google.com/github/2004-tanu/AI-based-Innovation-and-Product-Development.io/blob/main/AIPD_06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
!pip install pandas scikit-learn

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

from sklearn.metrics import accuracy_score, precision_score, recall_score, classification_report

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [6]:
df = pd.read_csv('movies.csv')
df.head()

   User_ID  Movie_ID                Movie_Name   Genre  Rating
0        1       101  The Shawshank Redemption   Drama       4
1        1       102             The Godfather   Crime       3
2        1       103           The Dark Knight  Action       5
3        2       104              Pulp Fiction   Crime       3
4        2       105              Forrest Gump   Drama       4

In [7]:
df.columns

Index(['User_ID', 'Movie_ID', 'Movie_Name', 'Genre', 'Rating'], dtype='object')

In [10]:
df.isnull().sum()

User_ID       0
Movie_ID      0
Movie_Name    0
Genre         0
Rating        0
dtype: int64

In [ ]:
# Data Preprocessing

In [11]:
# Encode categorical columns
le_user = LabelEncoder()
le_movie = LabelEncoder()
le_name = LabelEncoder()
le_genre = LabelEncoder()

df['User_ID'] = le_user.fit_transform(df['User_ID'])
df['Movie_ID'] = le_movie.fit_transform(df['Movie_ID'])
df['Movie_Name'] = le_name.fit_transform(df['Movie_Name'])
df['Genre'] = le_genre.fit_transform(df['Genre'])

# Convert rating into classification (like/dislike)
df['Rating_Class'] = df['Rating'].apply(lambda x: 1 if x >= 3 else 0)

df.head()

   User_ID  Movie_ID  Movie_Name  Genre  Rating  Rating_Class
0        0         0          51      5       4             1
1        0         1          39      4       3             1
2        0         2          36      0       5             1
3        1         3          28      4       3             1
4        1         4          12      5       4             1

In [12]:
# Define Features and Target

X = df[['User_ID', 'Movie_ID', 'Movie_Name', 'Genre']]
y = df['Rating_Class']

In [13]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [14]:
# Feature Scaling

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [15]:
# KNN Model

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

y_pred_knn = knn.predict(X_test)

print("KNN Results:")
print("Accuracy:", accuracy_score(y_test, y_pred_knn))
print("Precision:", precision_score(y_test, y_pred_knn))
print("Recall:", recall_score(y_test, y_pred_knn))
print("\nClassification Report:\n", classification_report(y_test, y_pred_knn))

KNN Results:
Accuracy: 1.0
Precision: 1.0
Recall: 1.0

Classification Report:
               precision    recall  f1-score   support

           1       1.00      1.00      1.00        13

    accuracy                           1.00        13
   macro avg       1.00      1.00      1.00        13
weighted avg       1.00      1.00      1.00        13

In [16]:
# SVM Model

svm = SVC(kernel='linear')
svm.fit(X_train, y_train)

y_pred_svm = svm.predict(X_test)

print("SVM Results:")
print("Accuracy:", accuracy_score(y_test, y_pred_svm))
print("Precision:", precision_score(y_test, y_pred_svm))
print("Recall:", recall_score(y_test, y_pred_svm))
print("\nClassification Report:\n", classification_report(y_test, y_pred_svm))

SVM Results:
Accuracy: 1.0
Precision: 1.0
Recall: 1.0

Classification Report:
               precision    recall  f1-score   support

           1       1.00      1.00      1.00        13

    accuracy                           1.00        13
   macro avg       1.00      1.00      1.00        13
weighted avg       1.00      1.00      1.00        13

In [17]:
# Compare Models

print("Model Comparison:")
print("KNN Accuracy:", accuracy_score(y_test, y_pred_knn))
print("SVM Accuracy:", accuracy_score(y_test, y_pred_svm))

Model Comparison:
KNN Accuracy: 1.0
SVM Accuracy: 1.0